/**
 * Error type definitions
 */

export enum ErrorCode {
  // Authentication errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_BANNED = 'ACCOUNT_BANNED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',

  // Registration errors
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  INVALID_EMAIL = 'INVALID_EMAIL',
  TERMS_NOT_ACCEPTED = 'TERMS_NOT_ACCEPTED',

  // OAuth errors
  OAUTH_ERROR = 'OAUTH_ERROR',
  OAUTH_STATE_MISMATCH = 'OAUTH_STATE_MISMATCH',
  OAUTH_CODE_INVALID = 'OAUTH_CODE_INVALID',
  OAUTH_PROVIDER_NOT_SUPPORTED = 'OAUTH_PROVIDER_NOT_SUPPORTED',

  // MFA errors
  MFA_REQUIRED = 'MFA_REQUIRED',
  MFA_CODE_INVALID = 'MFA_CODE_INVALID',
  MFA_CODE_EXPIRED = 'MFA_CODE_EXPIRED',
  MFA_NOT_ENABLED = 'MFA_NOT_ENABLED',
  MFA_ALREADY_ENABLED = 'MFA_ALREADY_ENABLED',

  // Rate limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  BRUTE_FORCE_DETECTED = 'BRUTE_FORCE_DETECTED',

  // CSRF
  CSRF_TOKEN_INVALID = 'CSRF_TOKEN_INVALID',
  CSRF_TOKEN_MISSING = 'CSRF_TOKEN_MISSING',

  // General errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export interface AuthError {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
  statusCode?: number;
  timestamp?: Date;
}

export interface ValidationError {
  field: string;
  message: string;
  code?: string;
}

export interface ValidationErrors {
  errors: ValidationError[];
}
